### ISSUE TITLE
MariaDB Script Copy Command

### ISSUE THREAD

**Issue by gknoop** [CVJoint/traefik2#8]
I have had no success running the command specified in the mariadb yml for database backups:
`docker run --rm --entrypoint cat dsteinkopf script/backup-all-mysql /backup-all-mysql.sh  > $USERDIR/docker/mariadb/backup-all-mysql.sh`

Attempting to do so yields the following output:

> Unable to find image 'dsteinkopf:latest' locally
> docker: Error response from daemon: pull access denied for dsteinkopf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.

**Comment by CVJoint** [comment]
There was a typo/paste error in that command. The image name should be `dsteinkopf/backup-all-mysql` but there was an unnecessary `" script"` added by accident.

The correct command is:
`docker run --rm --entrypoint cat dsteinkopf/backup-all-mysql /backup-all-mysql.sh  > $USERDIR/docker/mariadb/backup-all-mysql.sh`

Thanks, I pushed the fix.

**Comment by gknoop** [comment]
Thank you for doing so! This repo was very helpful for getting my RPi4 set up with everything behind Traefik and (some behind) Authelia.
